In [2]:
type('hello')

str

In [4]:
class Man:
    def __init__(self, name):
        self.name = name
        print("초기화 되었습니다.")
    
    def hello(self):
        print("Hello "+self.name+"!")
    
    def goodbye(self):
        print("Good-Bye "+self.name+"!")

In [5]:
m = Man("David")

초기화 되었습니다.


In [6]:
m.hello()

Hello David!


In [7]:
m.goodbye()

Good-Bye David!


In [8]:
import numpy as np

In [15]:
x=np.array([1.0,2.0,3.0])

In [16]:
type(x)

numpy.ndarray

In [17]:
print(x)

[ 1.  2.  3.]


In [18]:
y=np.array([2.0,4,6])

In [19]:
x+y

array([ 3.,  6.,  9.])

In [20]:
x-y

array([-1., -2., -3.])

In [21]:
x*y

array([  2.,   8.,  18.])

In [22]:
x/y

array([ 0.5,  0.5,  0.5])

In [23]:
x*4

array([  4.,   8.,  12.])

In [24]:
x

array([ 1.,  2.,  3.])

In [25]:
A = np.array([[1,2],[3,4]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
A.shape

(2, 2)

In [28]:
A.dtype

dtype('int64')

In [29]:
B = np.array([[3,0],[0,6]])

In [30]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [31]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [33]:
x=np.array([[1,2],[3,4],[5,6]])

In [34]:
x.shape

(3, 2)

In [35]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [36]:
x=x.flatten()

In [37]:
print(x)

[1 2 3 4 5 6]


In [38]:
x[np.array([0,2,4])]

array([1, 3, 5])

In [39]:
x>3

array([False, False, False,  True,  True,  True], dtype=bool)

In [40]:
x[x>3]

array([4, 5, 6])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(0, 6, 0.1)
y = np.sin(x)
plt.plot(x,y)
plt.show()

In [ ]:
print(x)

In [ ]:
print("hh")