In [1]:
import numpy as np
from numpy import log
from scipy.optimize import *
import matplotlib.pyplot as plt

In [2]:


a = np.array([1,2,3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a = np.arange(1,7)

In [5]:
print(a)

[1 2 3 4 5 6]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
a = a.reshape(2,3)

In [11]:
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
print(a.shape)

(2, 3)


In [24]:
b = a.reshape(-1,1)

print(b.T)

[[1 2 3 4 5 6]]


In [14]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
c = np.ones((2,3))

In [17]:
print(c)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [18]:
b = np.eye(3)

In [19]:
print(b)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [22]:
b.T

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
b


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
b.ravel()  # 행렬을 벡터로 만들어 준다.

array([1, 2, 3, 4, 5, 6])

In [29]:
np.arange(1,7).reshape(2,3).ravel().shape

(6,)