In [1]:
import tensorflow as tf
print(tf.__version__)

1.2.0


In [17]:
#x = tf.placeholder(tf.float32, shape=[None,2], name = "x")
#y_ = tf.placeholder(tf.float32, shape=[None,2], name="y_")

#truncated_normal은 0을 평균으로 정규분포하는 임의의 숫자를 할당한다. 
X  = tf.Variable(tf.truncated_normal(shape=[2,2]), dtype=tf.float32, name="w")
X2 = tf.Variable(tf.random_normal(shape=[3,1]), name="X2")
X3 = tf.Variable(tf.random_normal([3]), name = "x3")

In [18]:
sess = tf.Session()

#아래의 global_variables_initializer()을 꼭 해줘야 한다.
sess.run(tf.global_variables_initializer())
x_val = sess.run(X)
print(x_val)

print("="*80)

x2_val = sess.run(X2)
print(x2_val)

print("=" * 80)
x3_val = sess.run(X3)
print(x3_val)

[[ 1.67744899 -0.08626098]
 [ 0.93541199 -1.06239355]]
[[-0.45543519]
 [-0.08910601]
 [ 0.70412642]]
[-1.88180792 -0.17997932 -0.21033059]
