In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.2.0


In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.13.0


In [6]:
data = [1.0, 2.0, 3.0, 4.0]
print(type(data))

<class 'list'>


In [7]:
arr = np.array(data)

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
data2D = [[1,2,3,4],[5,6,7,8]]

In [15]:
arr2D = np.array(data2D)

In [16]:
print(type(data2D))

<class 'list'>


In [17]:
np.array(data2D)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
print(arr.ndim)

1


In [19]:
print(arr2D.ndim)

2


In [20]:
arr.shape

(4,)

In [21]:
arr2D.shape

(2, 4)

In [22]:
arr.dtype

dtype('float64')

In [23]:
print(arr.dtype)

float64


In [24]:
z1 = np.zeros(10)

In [25]:
z1

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
z1.shape

(10,)

In [27]:
z1.ndim

1

In [29]:
z1 = np.zeros((20,20))

In [30]:
z1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  

In [31]:
z1.shape

(20, 20)

In [32]:
z1.ndim

2

In [38]:
np.random.randn(5,3)

array([[ 0.16169623,  1.08478129, -1.01704382],
       [ 1.53433382, -0.02760368,  0.17287194],
       [-0.84938803, -0.07341176, -0.13785906],
       [ 0.89757657, -1.31796126, -0.33335912],
       [ 0.37401454, -0.61979637,  0.08374275]])

In [39]:
for n in range(10):
    print(np.random.randn(5,3))    

[[ 0.60162619  0.72716779  0.46993444]
 [ 1.09342762  1.10066117 -1.39691111]
 [-0.22871387 -1.54894706  1.74185038]
 [ 0.3484616   0.03889057  1.92031735]
 [ 1.2797703   1.80448325 -0.05106039]]
[[-0.11554929 -0.13893641 -1.51593231]
 [-0.98630772  0.29189478 -0.94205574]
 [ 0.85947342 -0.24831341  0.08106275]
 [-1.13267597 -1.31168813  1.26729427]
 [ 1.63121675 -1.65590259 -0.66847073]]
[[ 0.27438201 -0.81466403 -0.62817076]
 [ 1.01247404 -0.11140857  0.2979867 ]
 [ 0.88691895 -1.10443563 -0.41223017]
 [-0.30736087 -0.48874913 -0.37032132]
 [ 0.43748983  1.36869559 -0.32069384]]
[[ 1.30234143 -0.52416728 -0.29232251]
 [ 0.18520958 -1.12006901  1.39232024]
 [ 0.25753332  1.80048584 -0.51019894]
 [ 2.71927994  0.07299181  0.87413351]
 [-0.75053264  1.28815113 -2.16137054]]
[[-0.62385161  0.0260549  -0.25934545]
 [-1.15498511  0.24101391 -1.06619448]
 [ 1.11480017  1.61981677 -0.20809607]
 [ 0.59549533 -0.85141771  0.27321219]
 [ 1.0098043  -1.22276436  0.38457044]]
[[  1.35687169e+00  

In [40]:
t1 = np.array([1,2,3,4,5])

In [41]:
type(t1)

numpy.ndarray

In [42]:
t1.dtype

dtype('int64')

In [44]:
t1.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.])

In [48]:
type(t1.astype(np.float64).astype(np.str)[0])

numpy.str_

In [50]:
n1 = np.array([1,2,3,4,5])

In [52]:
n1.mean()

3.0

In [53]:
n1.max()

5

In [54]:
n1.sum()

15

In [55]:
a1 = np.array([1,2,3,4])

In [56]:
a1.shape

(4,)

In [57]:
a1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [58]:
a2 = a1.reshape(2,2)

In [59]:
a2.shape

(2, 2)

In [62]:
a2

array([[1, 2],
       [3, 4]])

In [61]:
a1

array([1, 2, 3, 4])

In [63]:
a1 = np.array([[1,2],[3,4],[5,6]])

In [64]:
a1[1]

array([3, 4])

In [66]:
a1[1:2]

array([[3, 4]])

In [73]:
a1[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
a1[:-1]

array([[1, 2],
       [3, 4]])

In [82]:
a1[1:,1:]

array([[4],
       [6]])

In [83]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
a1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [85]:
np.matmul(a1,a1.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [86]:
np.dot(a1, a1.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])