In [1]:
import tensorflow as tf
print(tf.__version__)

1.2.0


In [55]:
"""
아래는 

1 1 1
1 1 1 

행렬이다. 
"""

x = [[1,1,1],
     [1,1,1]]

y = [[[ 1, 2, 3],
      [40,20,30]],
     [[4,70,6],
      [7, 8,9]]]

In [56]:
sum = tf.reduce_sum(x)
sum1 = tf.reduce_sum(x, reduction_indices = 1)
sum2 = tf.reduce_sum(x, reduction_indices = 0)
sum3 = tf.reduce_sum(x, reduction_indices = 1, keep_dims = True)
sum4 = tf.reduce_sum(x, reduction_indices = [0, 1])
sum5 = tf.reduce_sum(x, reduction_indices = [1, 0])

In [57]:
sess = tf.Session()
print(sess.run(sum))
print(sess.run(sum1))
print(sess.run(sum2))
print(sess.run(sum3))
print(sess.run(sum4))
print(sess.run(sum5))

6
[3 3]
[2 2 2]
[[3]
 [3]]
6
6


In [58]:
#행렬에서 가장큰 값이 있는 인덱스를 리턴한다.
#벡터면 그냥 0써주면 된다.
sess.run(tf.arg_max(y,2))

array([[2, 0],
       [1, 2]])