In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.13.0


###### 파이썬에는 배열이라는 자료구조가 존재하지 않는다. 
###### 그래서 배열의 이점을 누릴 수 없다. 

In [3]:
a = np.array(range(10)) #파이썬의 배열을 입력 하면 넘파이 배열을 반환한다. 

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(a)

numpy.ndarray

In [6]:
b = [1,2,3]

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [12]:
2 * a + b

array([12, 24, 36])

In [13]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [15]:
np.log(b)

array([ 2.30258509,  2.99573227,  3.40119738])

In [16]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001])

In [17]:
b = np.array([[0,1,2],[3,4,5]])

In [18]:
b.shape

(2, 3)

In [19]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
len(b)

2

In [21]:
len(b[0])

3

In [22]:
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])

In [23]:
c.shape

(2, 3, 4)

In [24]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [25]:
n = np.array([[0,0,1],[1,0,0]])

In [27]:
np.argmax(n,axis=0)

array([1, 0, 0])

In [28]:
print(c.ndim)

3


In [29]:
print(c.shape)

(2, 3, 4)


In [31]:
a = np.array(1)

In [32]:
a

array(1)

In [33]:
a.ndim

0

In [34]:
a.shape

()

In [38]:
a = np.array([1,2,3])

In [39]:
a.ndim

1

In [40]:
a.shape

(3,)

In [41]:
a = np.array([[0,1,2],
              [3,4,5]])

In [42]:
a.shape

(2, 3)

In [43]:
a.ndim

2

## 콤마로 구분된 차원을 축(axis)이라고도 한다. 

In [48]:
a[0,2]

2

In [50]:
a[-1,-1]  # 마지막 행의 마지막 열

5

In [56]:
a = np.array([[0,1,2,3],
              [4,5,6,7]])

In [57]:
a[0,:]

array([0, 1, 2, 3])

In [58]:
a[1,:]

array([4, 5, 6, 7])

In [59]:
a[1,:2]

array([4, 5])

In [60]:
a[:,1:3]

array([[1, 2],
       [5, 6]])

##### fancy indexing

In [62]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [63]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [67]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) * 10
idx = np.array([0, 2, 4, 6, 8]) #위의 ndarray의 원소들의 인덱스들로 구성되어야 한다. 
a[idx]

array([ 0, 20, 40, 60, 80])

In [68]:
a = np.array([0, 1, 2, 3]) * 10
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([ 0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [70]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [72]:
a[[2, 0, 1], :] #2번인덱스 0번인덱스 1번인덱스 순으로 행을 정렬한다. 

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [77]:
x = np.array([1.,2,3])

In [78]:
x.dtype

dtype('float64')

In [79]:
np.exp(-np.inf)

0.0

In [80]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [82]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
np.zeros_like(3)

array(0)

In [86]:
np.array([1,2,3],dtype='float64')

array([ 1.,  2.,  3.])

In [89]:
b = np.zeros((2,3,4),dtype='f8')

In [90]:
b

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [98]:
c = np.zeros(5, dtype="S4")

In [99]:
c[0] = "abcd"
c[1] = "ABCDEF"  #EF는잘린다.

In [100]:
c

array([b'abcd', b'ABCD', b'', b'', b''],
      dtype='|S4')

In [101]:
np.array([1,2,3],dtype=np.float32)

array([ 1.,  2.,  3.], dtype=float32)

In [102]:
np.array([1,2,3],dtype=np.int32)

array([1, 2, 3], dtype=int32)